# Generated by Django 3.2.4 on 2021-07-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_listing_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='catagory',
            field=models.CharField(blank=True, choices=[('Camping Equipment', 'Camping Equipment'), ('kayaks and Canoes', 'kayaks and Canoes'), ('Fishing Equipment', 'Fishing Equipment'), ('Sports Equipment', 'Sports Equipment'), ('Snow Sports Equipment', 'Snow Sports Equipment'), ('Other', 'Other'), (None, 'Choose a Catagory')], max_length=21, null=True),
        ),
    ]
