# Generated by Django 3.2.4 on 2021-07-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210707_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='final_rent_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='init_rent_date',
            field=models.DateField(auto_now=True),
        ),
    ]
