# Generated by Django 3.2.4 on 2021-07-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210707_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='final_rent_date',
            field=models.DateField(auto_now=True, verbose_name='final rent date'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='init_rent_date',
            field=models.DateField(auto_now=True, verbose_name='Init rrent date'),
        ),
    ]
