# Generated by Django 3.2.4 on 2021-07-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_listing_available_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_per_night',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
