# Generated by Django 3.2.4 on 2021-07-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_listing_price_per_night'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='listing',
            name='price_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
