# Generated by Django 3.2.4 on 2021-07-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210713_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_imgs',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
